### ISSUE TITLE
login fail treatment

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [otsuarez/mkdocs_auth#4]
If I incorrectly insert my credentials, I am not able to login again. 

Have you treated this error?

**Comment by otsuarez** [comment]
The project uses just standard http basic authentication. How to clean that data depends on the browser. I just open an incognito windows when developing, if I need to reset that info, I'll just close it and open a new one (make sure not to have any other incognito windows open, just closed them all and open a new one).
